---
title: "dplyr"
author: "huifang"
date: "19 June 2019"
output: html_document
---
#chapter6 data wrangling  dplyr

```{r}
library(tidyverse)  

```

load data

```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv') 



```


```{r}
gapminder
head(gapminder) # shows first 6
tail(gapminder) # shows last 6

head(gapminder, 10) # shows first X that you indicate
tail(gapminder, 12) # guess what this does!



```

```{r}

str(gapminder) # ?str - displays the structure of an object

```


```{r}
names(gapminder)
dim(gapminder)    # ?dim dimension
ncol(gapminder)   # ?ncol number of columns
nrow(gapminder)   # ?nrow number of rows

```


```{r}
summary(gapminder)

library(skimr) # install.packages('skimr')
skim(gapminder)

```

```{r}
install.packages("skimr")
```

Look at the variables inside a data.frame

```{r}
gapminder$lifeExp # very long! hard to make sense of...
head(gapminder$lifeExp) # can do the same tests we tried before
str(gapminder$lifeExp) # it is a single numeric vector
summary(gapminder$lifeExp) # same information, formatted slightly differently

```


dplyr basics

```{r}
filter(gapminder, lifeExp < 29)

```


```{r}
filter(gapminder, country == "Mexico")
```

```{r}
filter(gapminder, country %in% c("Mexico", "Peru"))

```

```{r}
filter(gapminder, country == "Mexico", year == 2002)

```

```{r}
x <- filter(gapminder, country == "Brazil", year > 1986, year<2008)  
mean(x$lifeExp)  
```


```{r}
select(gapminder, year, country, lifeExp) 



```
```{r}
select(gapminder, -continent, -lifeExp) # you can use - to deselect columns

```


```{r}
gap_cambodia  <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp) 

```


```{r}
gapminder %>% head()
gapminder %>% head(3)
```

```{r}
#%>%  ctrl+shift+m
```


```{r}
## instead of this...
gap_cambodia  <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp) 

## ...we can do this
gap_cambodia  <- gapminder %>% filter(country == "Cambodia")
gap_cambodia2 <- gap_cambodia %>% select(-continent, -lifeExp) 

```

```{r}
gap_cambodia  <- gapminder %>% 
  filter(country == "Cambodia") %>%
  select(-continent, -lifeExp) 

```

mutate() adds new variables

```{r}
gapminder %>%
  mutate(gdp = pop * gdpPercap)
 #same as: mutate(gapminder, gdp=pop*gdpPercap)
```


```{r}
gapminder %>%
  filter(continent == "Asia",
         year == 2007) %>%
  mutate(pop_thousands = pop/1000) %>%
  select(country, year, pop_thousands) #this cleans up the dataframe but isn't necessary

```


group_by() operates on groups
```{r}
gapminder %>%
  filter(year == 2002) %>%
  group_by(continent) %>% 
  mutate(cont_pop = sum(pop))

```


summarize() with group_by()
```{r}
gapminder %>%
  group_by(continent) %>%
  summarize(cont_pop = sum(pop)) %>%
  ungroup()


```

```{r}
gapminder %>%
  group_by(continent, year) %>%
  summarize(cont_pop = sum(pop))

```

arrange() orders columns
```{r}
gapminder %>%
  group_by(continent, year) %>%
  summarize(cont_pop = sum(pop)) %>%
  arrange(year)

```

```{r}
gapminder %>%
  mutate(gdp = pop * gdpPercap) %>%
  group_by(continent) %>%
  mutate(max_gdp = max(gdp)) %>%
  filter(gdp == max_gdp)

```

```{r}

gapminder %>%
  mutate(gdp = pop * gdpPercap) %>%
  group_by(lifeExp) %>%
  mutate(max_gdp = max(gdp)) %>%
  filter(gdp == max_gdp)



```


All together now
```{r}


```






